### PR TITLE
New content for mmrm pages

### PR DESCRIPTION
**Pull request by yonicd**
Hi @statasaurus @DrLynTaylor this PR is for the content re the `mmrm`.

Let me know if any formatting or content changes should be made

### CODE REVIEW

**Comment by yonicd** [comment]
Not sure why, but `{knitr}` is getting 404 when trying to install from `CRAN`, which is causing build to fail.

**Comment by DrLynTaylor** [comment]
> Not sure why, but `{knitr}` is getting 404 when trying to install from `CRAN`, which is causing build to fail.

@yonicd   Thank you so much for your quick work.  I think this is the same issue Chi & I got when trying to render.  It could be something to do with the renv file.  @statasaurus when you are back from the conferences this week,  perhaps you, me, @andreaczhang  and @yonicd  could meet up, check the build & content and then we can get this MMRM work included in the repo.

**Comment by statasaurus** [comment]
Cause there were a few other pull requests with renv issues so I just rolled them together into a pull request. But, the update is now on the website. Thank you so much for this contribution!!

**Comment by yonicd** [comment]
@statasaurus it looks like the content that was here didnt make it to the site

**Comment by statasaurus** [comment]
let me add that in thank you for raising this

**Comment by statasaurus** [comment]
Sorry for this taking so long, I have now added the file

**Pull request closed without merging**
