### PR TITLE
Non-proportional hazards-weighted-log-rank-R

### PR DESCRIPTION
**Pull request by sharonav8**
Implementation of weighted log rank test in R using `survival` and `nphRCt` packages

### CODE REVIEW

**Comment by LucaAnholt** [comment]
Hey @sharonav8, I've created a pull request in your forked repository https://github.com/sharonav8/CAMIS/pull/1 in order to help try resolve some of these merge conflicts regarding renv. I've left a comment on that pull request linked explaining what happened in more detail as well as some instructions on accepting that pull request to update this PR here

**Review by statasaurus — CHANGES_REQUESTED** [review]
You just need to remove the format at the top then all is good. I added in some session info as well

**Review by sharonav8 — COMMENTED** [review]
The requested change is made

**Review by statasaurus — APPROVED** [review]
Looks great thanks

**Pull request merged**
